# Generated by Django 3.2.4 on 2021-06-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_rename_name_appointment_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pname',
            new_name='name',
        ),
    ]
