# Generated by Django 3.2.4 on 2021-06-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_rename_pname_appointment_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Department1',
        ),
        migrations.RenameModel(
            old_name='DoctorList',
            new_name='DoctorList1',
        ),
    ]
