# Generated by Django 3.2.4 on 2021-06-17 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_auto_20210617_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department1',
            new_name='Department',
        ),
        migrations.RenameModel(
            old_name='DoctorList1',
            new_name='DoctorList',
        ),
    ]
